Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,11 +3,10 @@ name: Test Cars CI
 on:
   push:
     branches:
-      - main 
+      - main
   pull_request:
     branches:
-      - main  
-  workflow_dispatch: 
+      - main
 
 jobs:
   build_image:
@@ -27,12 +26,13 @@ jobs:
         key: ${{ runner.os }}-buildx-${{ github.sha }}
         restore-keys: |
           ${{ runner.os }}-buildx-
+
     - name: Build Docker image
       run: docker build -t test-cars . --build-arg BUILDKIT_INLINE_CACHE=1
 
   TestApi:
     runs-on: ubuntu-latest
-    needs: build_image 
+    needs: build_image
 
     steps:
     - name: Check out the code
@@ -45,8 +45,17 @@ jobs:
       run: |
         docker run --name test-cars-api test-cars bash -c "pytest -s -v tests/test_app.py > tests/results/api_results.txt"
       
+    - name: Check if API test results exist
+      run: |
+        if [ -f tests/results/api_results.txt ]; then
+          echo "API test results exist."
+        else
+          echo "API test results are missing!"
+          exit 1
+        fi
+
     - name: Upload API test results
-      uses: actions/upload-artifact@v3
+      uses: actions/upload-artifact@v2 
       with:
         name: api-results
         path: tests/results/api_results.txt 
@@ -60,15 +69,23 @@ jobs:
       uses: actions/checkout@v2
 
     - name: Create results directory
-      run: mkdir -p tests/results 
+      run: mkdir -p tests/results  
 
     - name: Run UI tests
       run: |
         docker run --name test-cars-ui test-cars bash -c "pytest -s -v tests/test_ui.py > tests/results/ui_results.txt"
       
+    - name: Check if UI test results exist
+      run: |
+        if [ -f tests/results/ui_results.txt ]; then
+          echo "UI test results exist."
+        else
+          echo "UI test results are missing!"
+          exit 1
+        fi
+
     - name: Upload UI test results
-      uses: actions/upload-artifact@v3
+      uses: actions/upload-artifact@v2  
       with:
         name: ui-results
-        path: tests/results/ui_results.txt  
-
+        path: tests/results/ui_results.txt 
